# Generated by Django 4.2.3 on 2023-08-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_category_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="names",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
